language: cpp
sudo: required
compiler:
  - g++
cache:
  apt: true
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: mkdir build && cd build && cmake .. && make
